apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-master
  namespace: kubernetes-cluster-nitingoyal
  labels:
    branch: master
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: nitingoyal/samplenodeapp:27
        ports:
        - containerPort: 7100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-develop
  namespace: kubernetes-cluster-nitingoyal
  labels:
    branch: develop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: nitingoyal/samplenodeapp:27
        ports:
        - containerPort: 7100

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-master
  namespace: kubernetes-cluster-nitingoyal
  labels:
    branch: master
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 7100
      nodePort: 30157

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-develop
  namespace: kubernetes-cluster-nitingoyal
  labels:
    branch: develop
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 7100
      nodePort: 30158
